name: Daily Commit

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a new commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          date >> daily-commit.txt
          git add daily-commit.txt
          git commit -m "Daily commit $(date)"
          git push
